# Online IDE configuration (safe to delete)

tasks:
  - before: |
      npm install
      export MO_DEV_HIDE_URLS=1 # hide Candid UI links
      echo 'export MO_DEV_HIDE_URLS=1' >> ~/.bashrc
      export PATH="$HOME/bin:$PATH"
      echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
      sudo apt-get update && sudo apt-get install -q -y libunwind-dev 
      npm i -g ic-mops
      mops install
      DFXVM_INIT_YES=true sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"

    command: |
      echo "Installation complete. Please close this terminal and open a new one to complete the setup and start working on your project."

vscode:
  extensions:
    - dfinity-foundation.vscode-motoko

ports:
  - name: Replica
    port: 4943
    visibility: public
    onOpen: ignore
